### ISSUE TITLE
smooth scrolling

### ISSUE THREAD

**Issue by jgobi** [getgrav/grav-theme-landio#19]
It would be good to incorporate a smooth scrolling when clicking on a link to a section. A single CSS rule would do this job, since this theme is focused in modern browsers:

```css
html {
  scroll-behavior: smooth;
}
```
